#!/usr/bin/env python3


import argparse
import subprocess

def main():
    parser = argparse.ArgumentParser(description=" ")

    parser.add_argument("command", choices=["install"], help="Command to execute (e.g., install)")
    parser.add_argument("package", type=str, help="Name of the package you want to download")

    args = parser.parse_args()
    print(f"Installing {args.package}...")

    for pkg in args.package.split(","):
        pkg = pkg.strip()
        command = f"pip install {pkg} --break-system-packages"

        try:
            subprocess.run(command, shell=True, check=True)
            print(f"Successfully installed {pkg}")
        except subprocess.CalledProcessError as e:
            print(f"Failed to install {pkg}: {e}")


if __name__== "__main__":
    main()